### ISSUE TITLE
not sure I understand the point of this middleware

### ISSUE THREAD

**Issue by CodisRedding** [mateodelnorte/servicebus-message-domain#1]
What I think I understand is that all code in handlers is run through a `domain` allowing for any exceptions to bubble up to a known error function? I keep coming back to the idea that  `servicebus-register-handlers` register function does the same thing... offer a way to catch exceptions thrown throughout the course of a handler?

**Comment by CodisRedding** [comment]
Also it seems `domain` has been deprecated https://nodejs.org/api/domain.html

**Comment by mateodelnorte** [comment]
This was created as a predecessor to `servicebus-register-handlers`. They don't need to be used together, so you likely wouldn't include it in your middleware stack if using the `sb-r-h`. 

And, yep. Domains have been deprecated, but they're still the best way of ensuring that errors that occur in a specific run of code can be bubbled up and associated with some correlationId. So this was the basis for tracing errors correlated to specific inputs.
